# Generated by Django 3.2.9 on 2021-12-04 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0003_alter_currency_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag_icon',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
